-- ==========================================================
-- Assignment 10: Car Rental & Fleet Booking System Database Schema
-- Execute this script in your Supabase SQL Editor
-- ==========================================================

-- 1. Vehicles Table
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    year INT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Sedan', 'SUV', 'Luxury', 'Hatchback', 'Electric')),
    daily_rate NUMERIC(10, 2) NOT NULL CHECK (daily_rate > 0),
    fuel_type TEXT NOT NULL,
    seating_capacity INT NOT NULL DEFAULT 5,
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'rented', 'maintenance')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Rentals / Bookings Table
CREATE TABLE IF NOT EXISTS rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- references Supabase auth.users
    vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE RESTRICT,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_cost NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'booked' CHECK (status IN ('booked', 'active', 'completed', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_date_range CHECK (end_date >= start_date)
);

-- Create Indexes for performance
CREATE INDEX IF NOT EXISTS idx_rentals_vehicle_id ON rentals(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_rentals_user_id ON rentals(user_id);
CREATE INDEX IF NOT EXISTS idx_rentals_dates ON rentals(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_vehicles_category ON vehicles(category);
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(status);

-- Sample Seed Data
INSERT INTO vehicles (brand, model, year, category, daily_rate, fuel_type, seating_capacity, status) VALUES
('Tesla', 'Model 3', 2024, 'Electric', 4500.00, 'EV', 5, 'available'),
('Toyota', 'Fortuner', 2023, 'SUV', 3800.00, 'Diesel', 7, 'available'),
('Mercedes-Benz', 'C-Class', 2024, 'Luxury', 7500.00, 'Petrol', 5, 'available'),
('Hyundai', 'i20', 2022, 'Hatchback', 1800.00, 'Petrol', 5, 'available'),
('Honda', 'City', 2023, 'Sedan', 2500.00, 'Petrol', 5, 'available');
